### ISSUE TITLE
Link to Manual Enrollment Portal KB page on Enroll Users page

### ISSUE THREAD

**Issue by nchan31** [cca/moodle-styles#15]
Can a link or information be added to direct instructors to the Portal KB page on manual enrollments?

![image](https://user-images.githubusercontent.com/93795394/192903584-b17c1a19-148d-4926-a483-bfc12be68a84.png)

This might be difficult since the Enroll Users page is already a pop-up window, but perhaps text similar to what pops up when changing one's name in a Moodle profile.

**Comment by nchan31** [comment]
@phette23  I decided to keep things simple.
`<div class="alert-primary" style="margin:6px;padding-left: 20px;padding-top: 12px;padding-right: 20px;padding-bottom: 12px;" id="yui_3_17_2_1_1674246567942_426">Learn more about <strong id="yui_3_17_2_1_1674246567942_425"><a href="https://portal.cca.edu/knowledge-base/moodle/managing-enrollment-in-moodle-courses/" target="_blank" id="yui_3_17_2_1_1674246567942_424">manual enrollments</a></strong>.</div>`

This would appear right after:
`<legend class="ftoggler">Enrollment options</legend>`

**Comment by phette23** [comment]
OK this is live on staging to try out!

<img width="798" alt="Screenshot 2023-01-24 at 11 16 47 AM" src="https://user-images.githubusercontent.com/1024833/214387608-ed4b150c-41c7-483a-863d-415c76eb9b2f.png">

The only thing I changed was removing the `id` attributes with long `yui...` strings. YUI is a JavaScript UI library which Moodle uses and all the element `id`s are meant to be unique on a page. These look like they're generated from a timestamp, and it's unlikely they'd cause a collision, but they're also not serving any purpose so it doesn't hurt to remove them.
