### ISSUE TITLE
edit settings links have changed

### ISSUE THREAD

**Issue by phette23** [cca/moodle-styles#18]
See Ming's comment: https://ccaweb.slack.com/archives/C02JGAUTA/p1677777261880309?thread_ts=1677718402.298059&cid=C02JGAUTA

The course backup/restore links are now in their own "course restore" submenu so it's unlikely that the current code in [additionalhtml/course-page.js][cpage] will work.

[cpage]: https://github.com/cca/moodle-styles/blob/main/additionalhtml/course-page.js#L22-L33

**Comment by phette23** [comment]
@nchan31 so I looked into this issue a little more. On 3.10, we hide the Restore, Filter, and Reset links in the course admin (gear) menu because they're kind of advanced. But we don't want to stop people from using them entirely, so they can still access them via the "more..." option.

On 4.0, it looks like we cannot do this, because the "more..." option is now directly linked off the course home page. So if we hide options in it, there is no other way to get to them. Can you double check?

**Comment by nchan31** [comment]
@phette23 So far, I'm not finding any alternate way, and the documentation I've found so far only refers to the Course Reuse option or methods that require admin permissions. I appreciate that the Import option is the one that shows up first when choosing Course Reuse, as that's the one that most users will use.
A possible option is to add a warning or information banner at the top of the page if someone selects one of the other options.

**Comment by phette23** [comment]
@nchan31 thanks for looking into it! I am just going to remove the code that hides these for now. We will see if people run into trouble with these tools and, if so, maybe add warnings as you suggest. For **Filters**, I wasn't even worried that people would mess something up, but it was relevant way too rarely to be in the main course admin menu. **Reset** already has a warning up top, though it does not use the alert styles.
